demopro/demoapp/urls.py
from django.urls import path
from .views import * 
from . import views

app_name = 'demoapp'
urlpatterns =[
    path('', HomeView.as_view(), name='home'),
    path('register/', Register.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('upload/', File_upload.as_view(), name='upload'),
    path('addapp/', AddAppView.as_view(), name='addapp'),
    path('detail/', MyDetail.as_view(), name='detail'),
    path('allapp/', AllAppDisplay.as_view(), name='allapp'),
    path('appdetail/<int:id>/', AppDetailView.as_view(), name='appdetail'),
    path('mypoints/', MyPoints.as_view(), name='mypoints'),
    path('workdone/', WorkDone.as_view(), name='workdone'),

    ### For rest Api
    path('total/', TotalView.as_view(), name=''),
]

demopro/demopro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("demoapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demopro/templates/addapp.html
{% extends 'base.html' %}
{%block title%}
Add App
{%endblock%}
{%block admin%}

<body>
    <h5>
        Add App
    </h5>
    <form method="post">
        {% csrf_token %}
        <input type="file" class="form-control" placeholder="image" id="image" name="image" />
        <input type="text" class="form-control" placeholder="category" id="category" name="category" />
        <input type="text" class="form-control" placeholder="subcategory" id="subcategory" name="subcategory" />
        <!-- {% for cat in category %} -->
        <!-- <input type="checkbox" class="form-control" placeholder="category" id="category" name="category" value="{{cat.name}}"/> -->
        <!-- {%endfor%} -->
        <!-- <input type="checkbox" class="form-control" placeholder="category" id="category" name="category" /> -->
        <input type="text" class="form-control" placeholder="points" id="points" name="points" />

        <div class="modal-footer">
            <button type="button" data-bs-dismiss="modal" class="btn btn-default" onclick="dismiss()">Cancel</button>
            <button type="submit" class="btn btn-primary" id="modalSubmit">Add App</button>
        </div>
    </form>
</body>
{%endblock%}

demopro/templates/allappdisplay.html
{% extends 'base.html' %}
{%block title%}
All Apps
{%endblock%}
{%block content%}
        {% for all in allapp %}
        <div class="card">
                <a href="{% url 'demoapp:appdetail' all.id %}"><img class="card-img-top" src="{{all.image.url}}" alt="Card image cap"></a>
                <div class="card-body">
                  <h5 class="card-title">{{all.category.name}}</h5>
                  <p class="card-text">{{all.subcategory.subname}}</p>
                  <p class="card-text">{{all.points}}</p>
                <hr>
                <a href="{% url 'demoapp:appdetail' all.id %}" style="text-align: center;"><button style="text-align: center;">Upload Screenshot</button></a>
                <hr>        
        </div>
        {%endfor%}
{%endblock%}

demopro/templates/appdetail.html
{% extends 'base.html' %}
{%block title%}
Apps Detail
{%endblock%}
{%block content%}
        <div class="card">
                <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">Category: {{product.category.name}}</h5>
                  <p class="card-text">Subcategory: {{product.subcategory.subname}}</p>
                  <p class="card-text">Points: {{product.points}}</p>
                <hr>
                </div>
                <h6>UPLOAD MULTIPLE IMAGES NOW</h6>
                <br>
                <form enctype='multipart/form-data' action="{% url 'demoapp:upload' %}" method='POST' class="dropzone dz" id="my-dropzone" >
                    {% csrf_token %}
                    <div class="fallback">
                      <input name="file" type="file"/>
                      <!-- <input name="file" type="file" multiple /> #for multiple -->
                      
                      <!-- <p class="card-text" name="appid">{{product.points}}</p> -->
                    </div>
                    <input name="appid" value="{{product.id}}" type="hidden">
                </form>
            <br>
{%endblock%}

demopro/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- custom css & js -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'main.js' %}" defer></script>

    <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">


    <title>Demo Django| {% block title %}{% endblock title %}</title>
</head>

<body>
    <div class="container mt-3">
        {% if request.user.is_authenticated %}
        {% if request.user.is_staff %}
        <div>
            <h6 style="text-align: center;">Hello ({{request.user.fullname}})</h6>
            <br>
        </div>
        <div class="row">
            <div class="col-3 mt-3">
                <li><a href="{% url 'demoapp:home' %}"> Home</a></li>
                <li><a href="{% url 'demoapp:addapp' %}"> AddApp</a></li>
                <li><a href="{% url 'demoapp:logout' %}"> Logout</a></li>
            </div>
            <div class="col-9">
                {% block admin %}
                {% endblock admin %}
            </div>
        </div>
            {% else %}
            <div>
                <h6 style="text-align: center;">Hello {{request.user.fullname}}</h6>
                <br>
            </div>
            <div class="row">
                
                <div class="col-3 mt-3">
                    <li><a href="{% url 'demoapp:home' %}"> Home</a></li>
                    <li><a href="{% url 'demoapp:detail' %}"> My Profile ({{request.user.fullname}})</a></li>
                    <li><a href="{% url 'demoapp:allapp' %}"> All Apps</a></li>
                    <li><a href="{% url 'demoapp:mypoints' %}"> My Points</a></li>
                    <li><a href="{% url 'demoapp:workdone' %}"> Work Done</a></li>
                    <li><a href="{% url 'demoapp:logout' %}"> Logout</a></li>
                </div>
                <div class="col-md-6">
                    {% block content %}
                    {% endblock content %}
                </div>
    </div>
    {% endif %}
    {% else %}
    <li><a href="{% url 'demoapp:register' %}"> Register</a></li>
    <li><a href="{% url 'demoapp:login' %}"> Login</a></li>
        {% endif %}
        
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>

demopro/templates/detail.html
{% extends 'base.html' %}
{%block title%}
My Details
{%endblock%}
{%block content%}
        
        <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Full Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Image</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">{{details.fullname}}</th>
                    <td>{{details.address}}</td>
                    <td>{{details.email}}</td>
                    <td>{{details.phonenumber}}</td>
                    <td><img class="card-img-top" src="{{details.profilepicture.url}}" alt="Card image cap"></td>
                  </tr>
                </tbody>
              </table>
{%endblock%}

demopro/templates/home.html
{% extends 'base.html' %}
{%block title%}
Home
{%endblock%}

{%block admin%}
<div>
  <h5>
    Hello Admin Welcome To the Home Page
  </h5>
</div>
{%endblock%}

{%block content%}
<div>
  <h5>
    Hello User Welcome To the Home Page
  </h5>
</div>
{%endblock%}

demopro/templates/login.html
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="w3l_banner_nav_right">
        <!-- login -->
        <div class="w3_login">
            <h3>Sign In & Sign Up</h3>
            <div class="w3_login_module">
                <div class="module form-module">
                    <div>
                    </div>
                    <div class="form">
                        <h2>Login account</h2>
                        <form action="#" method="post">
                            {% if error %}
                            <li style="color: red;">{{error}}</li>
                            {% endif %}
                            {% csrf_token %}
                            {{form.as_p}}
                            <button class="btn btn-primary">Login</button>

                        </form>
                        <p> or dont have account? <a
                                href="{% url 'demoapp:register' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register
                                here</a></p>
                    </div>
                    <!-- <div class="cta"><a href="">Forgot your password?</a></div> -->
                </div>
            </div>
            <script>
                $('.toggle').click(function () {
                    // Switches the Icon
                    $(this).children('i').toggleClass('fa-pencil');
                    // Switches the forms  
                    $('.form').animate({
                        height: "toggle",
                        'padding-top': 'toggle',
                        'padding-bottom': 'toggle',
                        opacity: "toggle"
                    }, "slow");
                });
            </script>
        </div>
        <!-- //login -->
    </div>
    <div class="clearfix"></div>
</body>

</html>

demopro/templates/mypoints.html
{% extends 'base.html' %}
{%block title%}
My Points
{%endblock%}
{%block content%}

     
    <table class="table">
        
        <thead>
          <tr>
            <th scope="col">Points</th>
          </tr>
        </thead>
        {% for p in mypoints %}
        <tbody>
          <tr>
            
            <th scope="row">{{p.point}}</th>
            
          </tr>
        </tbody>
        {%endfor%}
        <tr>
            <th scope="col">Total Points = {{total}}</th>
          </tr>
      </table>
 
{%endblock%}

demopro/templates/workdone.html
{% extends 'base.html' %}
{%block title%}
My Works
{%endblock%}
{%block content%}
        
        <table class="table">
                <thead>
                  <tr>
                    <th scope="col">App Name</th>
                    <th scope="col">App Subcategory</th>
                    <th scope="col">Points</th>
                    <th scope="col">Image</th>
                  </tr>
                </thead>
                <tbody>
                    {% for data in mypoints.all %}
                  <tr>
                    <th scope="row">{{data.app.category.name}}</th>
                    <th scope="row">{{data.app.subcategory.subname}}</th>
                    <td>{{data.point}}</td>
                    <td><img class="card-img-top" src="{{data.app.image.url}}" alt="Card image cap" style="width: 100px; height: 100px;"></td>
                  </tr>
                  {%endfor%}
                </tbody>
              </table>
{%endblock%}